name: amsafe
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  rename: ^3.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  geolocator: ^13.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  telephony: ^0.2.0
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
