import 'package:flutter/material.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

SizedBox sizedBoxHeight03 = SizedBox(height: Adaptive.h(0.35));
SizedBox sizedBoxHeight05 = SizedBox(height: Adaptive.h(0.5));
SizedBox sizedBoxHeight10 = SizedBox(height: Adaptive.h(1));
SizedBox sizedBoxHeight15 = SizedBox(height: Adaptive.h(1.5));
SizedBox sizedBoxHeight20 = SizedBox(height: Adaptive.h(2));
SizedBox sizedBoxHeight30 = SizedBox(height: Adaptive.h(3));
SizedBox sizedBoxHeight40 = SizedBox(height: Adaptive.h(4));
SizedBox sizedBoxHeight50 = SizedBox(height: Adaptive.h(5));
SizedBox sizedBoxHeight60 = SizedBox(height: Adaptive.h(6));
SizedBox sizedBoxHeight70 = SizedBox(height: Adaptive.h(7));
SizedBox sizedBoxHeight80 = SizedBox(height: Adaptive.h(8));
SizedBox sizedBoxHeight90 = SizedBox(height: Adaptive.h(9));
SizedBox sizedBoxHeight100 = SizedBox(height: Adaptive.h(10));
SizedBox sizedBoxHeight110 = SizedBox(height: Adaptive.h(11));
SizedBox sizedBoxHeight120 = SizedBox(height: Adaptive.h(12));
SizedBox sizedBoxHeight130 = SizedBox(height: Adaptive.h(13));
SizedBox sizedBoxHeight140 = SizedBox(height: Adaptive.h(14));
SizedBox sizedBoxWidth05 = SizedBox(width: Adaptive.w(0.5));
SizedBox sizedBoxWidth10 = SizedBox(width: Adaptive.w(1));
SizedBox sizedBoxWidth15 = SizedBox(width: Adaptive.w(1.5));
SizedBox sizedBoxWidth20 = SizedBox(width: Adaptive.w(2));
SizedBox sizedBoxWidth30 = SizedBox(width: Adaptive.w(3));
SizedBox sizedBoxWidth40 = SizedBox(width: Adaptive.w(4));
SizedBox sizedBoxWidth50 = SizedBox(width: Adaptive.w(5));
SizedBox sizedBoxWidth60 = SizedBox(width: Adaptive.w(6));
SizedBox sizedBoxWidth70 = SizedBox(width: Adaptive.w(7));
SizedBox sizedBoxWidth80 = SizedBox(width: Adaptive.w(8));
SizedBox sizedBoxWidth90 = SizedBox(width: Adaptive.w(9));
SizedBox sizedBoxWidth100 = SizedBox(width: Adaptive.w(10));
